services:
  - type: web
    name: Text-To-Speech-With-pyttsx3
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    buildCommand: ""
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
